apiVersion: v1
kind: Pod
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  containers:
  - name: vprodb
    image: visualpath/vprodb
    ports:
    - name: vprodb-port
      containerPort: 3306
